apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kanban-app
    group: backend
  name: kanban-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanban-app
  template:
    metadata:
      labels:
        app: kanban-app
        group: backend
    spec:
      containers:
      - image: wkrzywiec/kanban-app:k8s
        name: kanban-app
        ports:
        - containerPort: 8080
        #envFrom:
        #  - configMapRef:
        #      name: postgres-config
        env:
          #- name: DB_SERVER
          #  value: postgres
          # - name: POSTGRES_USER
          #   valueFrom:
          #     secretKeyRef:
          #       name: postgres-secret
          #       key: POSTGRES_USER
          # - name: POSTGRES_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: postgres-secret
          #       key: POSTGRES_PASSWORD
          - name: DB_SERVER
            value: postgres
          - name: POSTGRES_DB
            value: kanban
          - name: POSTGRES_PASSWORD
            value: kanban
          - name: POSTGRES_USER
            value: kanban
          - name: POSTGRES_HOST
            value: postgres
        resources:
          requests:
           memory: "256Mi"
           cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "500m"
