apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    group: db
data:
  # init.sql: |
  #   CREATE USER kanban WITH PASSWORD 'kanban';
  #   CREATE DATABASE kanban OWNER kanban;
  #   GRANT ALL PRIVILEGES ON DATABASE kanban TO kanban; ##.default.svc.cluster.local
  POSTGRES_HOST: postgres.default.svc.cluster.local
  POSTGRES_DB: kanban
  POSTGRES_USER: kanban
  POSTGRES_PASSWORD: kanban